version: "3.9"

services:
  synthtex-postgres:
    image: postgres:16
    container_name: synthtex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: synthtex_user
      POSTGRES_PASSWORD: synthtex_password
      POSTGRES_DB: synthtex_db
    volumes:
      - synthtex_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synthtex_user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  synthtex_pgdata:
