
services:

  synthtex-backend:
    build: ../apps/backend
    container_name: synthtex-backend
    restart: unless-stopped
    env_file:
      - ../apps/backend/.env
    ports:
      - "8000:8000"
    depends_on:
      synthtex-postgres:
        condition: service_healthy
      synthtex-redis:
        condition: service_healthy
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  synthtex-compiler:
    build: ../apps/compiler
    container_name: synthtex-compiler
    restart: unless-stopped
    env_file:
      - ../apps/compiler/.env
    depends_on:
      synthtex-postgres:
        condition: service_healthy
      synthtex-redis:
        condition: service_healthy
    command: ["uv", "run", "arq", "worker.WorkerSettings"]

  synthtex-postgres:
    image: postgres:16
    container_name: synthtex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: synthtex_user
      POSTGRES_PASSWORD: synthtex_password
      POSTGRES_DB: synthtex_db
    volumes:
      - synthtex_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", pg_isready -U synthtex_user -d synthtex_db]
      interval: 5s
      timeout: 5s
      retries: 5
    
  synthtex-redis:
    image: redis:7
    container_name: synthtex-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - synthtex_redisdata:/data
    command: ["redis-server", "--appendonly","yes"]
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  synthtex_pgdata:
  synthtex_redisdata:
